name: Create Docker Image

on: [push]

jobs:

  build-and-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/markcarrier/markcarrier.info/mwebserver:$GITHUB_SHA
    
    - name: Publish to github registry
      run: docker push docker.pkg.github.com/markcarrier/markcarrier.info/mwebserver:$GITHUB_SHA
